const viewInserts = "\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7369, 'SMITH', 'CLERK', 7902,TO_DATE('17-DEC-1980', 'DD-MON-YYYY'), 800, NULL, 20, 'RESEARCH', 'DALLAS');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7499, 'ALLEN', 'SALESMAN', 7698,TO_DATE('20-FEB-1981', 'DD-MON-YYYY'), 1600, 300, 30, 'SALES', 'CHICAGO');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7521, 'WARD', 'SALESMAN', 7698,TO_DATE('22-FEB-1981', 'DD-MON-YYYY'), 1250, 500, 30, 'SALES', 'CHICAGO');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7566, 'JONES', 'MANAGER', 7839,TO_DATE('2-APR-1981', 'DD-MON-YYYY'), 2975, NULL, 20, 'RESEARCH', 'DALLAS');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7654, 'MARTIN', 'SALESMAN', 7698,TO_DATE('28-SEP-1981', 'DD-MON-YYYY'), 1250, 1400, 30, 'SALES', 'CHICAGO');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7698, 'BLAKE', 'MANAGER', 7839,TO_DATE('1-MAY-1981', 'DD-MON-YYYY'), 2850, NULL, 30, 'SALES', 'CHICAGO');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7782, 'CLARK', 'MANAGER', 7839,TO_DATE('9-JUN-1981', 'DD-MON-YYYY'), 2450, NULL, 10, 'ACCOUNTING', 'NEW YORK');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7788, 'SCOTT', 'ANALYST', 7566,TO_DATE('09-DEC-1982', 'DD-MON-YYYY'), 3000, NULL, 20, 'RESEARCH', 'DALLAS');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7839, 'KING', 'PRESIDENT', NULL,TO_DATE('17-NOV-1981', 'DD-MON-YYYY'), 5000, NULL, 10, 'ACCOUNTING', 'NEW YORK');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7844, 'TURNER', 'SALESMAN', 7698,TO_DATE('8-SEP-1981', 'DD-MON-YYYY'), 1500, NULL, 30, 'SALES', 'CHICAGO');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7876, 'ADAMS', 'CLERK', 7788,TO_DATE('12-JAN-1983', 'DD-MON-YYYY'), 1100, NULL, 20, 'RESEARCH', 'DALLAS');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7900, 'JAMES', 'CLERK', 7698,TO_DATE('3-DEC-1981', 'DD-MON-YYYY'), 950, NULL, 30, 'SALES', 'CHICAGO');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7902, 'FORD', 'ANALYST', 7566,TO_DATE('3-DEC-1981', 'DD-MON-YYYY'), 3000, NULL, 20, 'RESEARCH', 'DALLAS');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC) VALUES (7934, 'MILLER', 'CLERK', 7782,TO_DATE('23-JAN-1982', 'DD-MON-YYYY'), 1300, NULL, 10, 'ACCOUNTING', 'NEW YORK');\n\
INSERT INTO EMP_DEPT_UPSERT_VIEW (DEPTNO, DNAME, LOC) VALUES (40, 'ACCOUNTING', 'NEW YORK');\n\
commit;\n\
select * from emp_dept_upsert_view\n"
  .replace(/\n/g, "<br>")

  export default viewInserts;