-- ==========================================
-- CREATE DEPARTMENT TABLE
-- Source: create_department_table.sql
-- ==========================================
CREATE TABLE "DEPARTMENT" 
   (	"DEPT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DEPT_CODE" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"ESTABLISHED" DATE, 
	"DETAILS" JSON
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "DEPT_CODE_UK" ON "DEPARTMENT" ("DEPT_CODE") 
  ;

CREATE UNIQUE INDEX "DEPT_ID_PK" ON "DEPARTMENT" ("DEPT_ID") 
  ;

CREATE UNIQUE INDEX "DEPARTMENT_DEPT_CODE_UQ" ON "DEPARTMENT" (UPPER("DEPT_CODE")) 
  ;

ALTER TABLE "DEPARTMENT" MODIFY ("DEPT_ID" NOT NULL ENABLE);

ALTER TABLE "DEPARTMENT" MODIFY ("DEPT_CODE" CONSTRAINT "DEPT_CODE_NN" NOT NULL ENABLE);

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "DEPT_ID_PK" PRIMARY KEY ("DEPT_ID")
  USING INDEX  ENABLE;


-- ==========================================
-- CREATE EMPLOYEE TABLE
-- Source: create_employee_table.sql
-- ==========================================
CREATE TABLE "EMPLOYEE" 
   (	"EMP_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMP_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPT_ID" NUMBER, 
	"COMMENTS" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "EMP_ID_PK" ON "EMPLOYEE" ("EMP_ID") 
  ;

CREATE INDEX "EMP_DEPARTMENT_IX" ON "EMPLOYEE" ("DEPT_ID") 
  ;

ALTER TABLE "EMPLOYEE" MODIFY ("EMP_ID" NOT NULL ENABLE);

ALTER TABLE "EMPLOYEE" MODIFY ("EMP_NAME" CONSTRAINT "EMP_NAME_NN" NOT NULL ENABLE);

ALTER TABLE "EMPLOYEE" MODIFY ("DEPT_ID" CONSTRAINT "EMP_DEPT_ID_NN" NOT NULL ENABLE);

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMP_ID_PK" PRIMARY KEY ("EMP_ID")
  USING INDEX  ENABLE;

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_EMPLOYEE_DEPT" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "DEPARTMENT" ("DEPT_ID") ENABLE;


-- ==========================================
-- CREATE PROJECT TABLE
-- Source: create_project_table.sql
-- ==========================================
CREATE TABLE "PROJECT" 
   (	"PROJ_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PROJ_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPT_ID" NUMBER, 
	"IS_ACTIVE" BOOLEAN
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "PROJ_ID_PK" ON "PROJECT" ("PROJ_ID") 
  ;

CREATE INDEX "PROJ_DEPARTMENT_IX" ON "PROJECT" ("DEPT_ID") 
  ;

ALTER TABLE "PROJECT" MODIFY ("PROJ_ID" NOT NULL ENABLE);

ALTER TABLE "PROJECT" MODIFY ("PROJ_NAME" CONSTRAINT "PROJ_NAME_NN" NOT NULL ENABLE);

ALTER TABLE "PROJECT" MODIFY ("DEPT_ID" CONSTRAINT "PROJ_DEPT_ID_NN" NOT NULL ENABLE);

ALTER TABLE "PROJECT" ADD CONSTRAINT "PROJ_ID_PK" PRIMARY KEY ("PROJ_ID")
  USING INDEX  ENABLE;

ALTER TABLE "PROJECT" ADD CONSTRAINT "FK_PROJECT_DEPT" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "DEPARTMENT" ("DEPT_ID") ENABLE;

-- ==========================================
-- INSERT DATA
-- Source: insert_data.sql
-- ==========================================
INSERT INTO DEPARTMENT (DEPT_CODE, ESTABLISHED, DETAILS) VALUES
    ('HR001', DATE '2001-04-13', JSON_OBJECT('location' VALUE 'Bldg 1', 'members' VALUE 25)),
    ('FN002', DATE '2002-06-20', JSON_OBJECT('location' VALUE 'Bldg 2', 'members' VALUE 20)),
    ('EN003', DATE '2000-11-01', JSON_OBJECT('location' VALUE 'Bldg 3', 'members' VALUE 40)),
    ('SA004', DATE '2005-01-15', JSON_OBJECT('location' VALUE 'Bldg 4', 'members' VALUE 18)),
    ('MK005', DATE '2003-12-07', JSON_OBJECT('location' VALUE 'Bldg 5', 'members' VALUE 15)),
    ('LG006', DATE '2010-03-31', JSON_OBJECT('location' VALUE 'Bldg 6', 'members' VALUE 5)),
    ('IT007', DATE '2001-09-23', JSON_OBJECT('location' VALUE 'Bldg 7', 'members' VALUE 30)),
    ('SP008', DATE '2015-05-05', JSON_OBJECT('location' VALUE 'Bldg 8', 'members' VALUE 12)),
    ('LG009', DATE '2012-07-14', JSON_OBJECT('location' VALUE 'Bldg 9', 'members' VALUE 10)),
    ('OP010', DATE '2008-08-01', JSON_OBJECT('location' VALUE 'Bldg 10', 'members' VALUE 22));
    COMMIT;

INSERT INTO PROJECT (PROJ_NAME, DEPT_ID, IS_ACTIVE) VALUES
    ('Onboarding', 1, TRUE),
    ('Audit2024', 2, FALSE),
    ('NewApp', 3, TRUE),
    ('SalesCampaign', 4, TRUE),
    ('SocialMediaPush', 5, FALSE),
    ('Compliance', 6, TRUE),
    ('UpgradeInfra', 7, TRUE),
    ('HelpdeskRevamp', 8, TRUE),
    ('FleetUpdate', 9, TRUE),
    ('ProcessReorg', 10, FALSE);
    COMMIT;

INSERT INTO EMPLOYEE (EMP_NAME, DEPT_ID, COMMENTS) VALUES
    ('Alice', 1,  'Strong analyst, quick learner.'),
    ('Bob', 2,  'CPA certification in progress.'),
    ('Carol', 3,  'Dev team lead for NewApp project.'),
    ('David', 4,  'Consistent sales over target.'),
    ('Eve', 5,  'Leads digital campaigns.'),
    ('Frank', 6,  'Subject matter expert in compliance.'),
    ('Grace', 7,  'Skilled in infrastructure upgrades.'),
    ('Heidi', 8,  'Customer support supervisor.'),
    ('Ivan', 9,  'Fleet manager - long tenure.'),
    ('Judy', 10,  'Operations management veteran.');
    COMMIT;


-- ==========================================
-- CREATE PROCEDURE
-- Source: create_procedure.sql
-- ==========================================
CREATE OR REPLACE EDITIONABLE PROCEDURE "PR_ADD_AND_ASSIGN_EMPLOYEE" (
      p_emp_name  IN VARCHAR2,
      p_dept_code IN VARCHAR2,
      p_comments  IN CLOB
  ) AS
      l_dept_id department.dept_id%TYPE;
  BEGIN
      SELECT dept_id
        INTO l_dept_id
        FROM department
       WHERE UPPER(dept_code) = UPPER(p_dept_code);

      INSERT INTO employee (
          emp_name,
          dept_id,
          comments
      )
      VALUES (
          p_emp_name,
          l_dept_id,
          p_comments
      );

  EXCEPTION
      WHEN NO_DATA_FOUND THEN
          raise_application_error(
              -20001,
              'Department code not found. Valid values: ' ||
              'EN003, FN002, HR001, IT007, LG006, LG009, ' ||
              'MK005, OP010, SA004, SP008'
          );
  END;
/
