-- Generated by ORDS REST Data Services 26.2.3.r2371104
-- Schema: DEMO_USER  Date: Thu Sep 17 07:11:13 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
   -- Warning: privileges do not protect modules during
   -- OAuth Client standalone export.
    
  ORDS.CREATE_ROLE(
      p_role_name=> 'my.test.role');

  ORDS_SECURITY.IMPORT_CLIENT(
      p_name             => 'my_test_oauth_client',
      p_client_id        => 'rP9btP7w5Md72r6iEK3Tog..',
      p_grant_type       => 'client_credentials',
      p_owner            => 'DEMO_USER',
      p_description      => 'my_test_oauth_client',
      p_origins_allowed  => NULL,
      p_redirect_uri     => NULL,
      p_support_email    => 'my_email@example.com',
      p_support_uri      => 'https://www.my-company.com/support',
      p_token_duration   => NULL,
      p_refresh_duration => NULL,
      p_code_duration    => NULL,
      p_privilege_names  => NULL);

   ORDS_SECURITY.GRANT_CLIENT_ROLE(
      p_client_name     => 'my_test_oauth_client',
      p_role_name => 'my.test.role');
COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;