
-- Generated by ORDS REST Data Services 26.2.3.r2371104
-- Schema: ORDSDEMO  Date: Tue Sep 29 08:10:52 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
   -- Warning: privileges do not protect modules during
   -- OAuth Client standalone export.
    
  ORDS.CREATE_ROLE(
      p_role_name=> 'my.test.role');
  l_roles(1) := 'my.test.role';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'my.test.priv',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'my.test.priv',
      p_description    => 'my.test.priv',
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;


  ORDS_SECURITY.IMPORT_CLIENT(
      p_name             => 'my.oauth.client',
      p_client_id        => 'qMdpq2WHzkzd1aPHawTmvw..',
      p_grant_type       => 'client_credentials',
      p_owner            => 'ORDSDEMO',
      p_description      => 'my.oauth.client',
      p_origins_allowed  => NULL,
      p_redirect_uri     => NULL,
      p_support_email    => 'test@email.com',
      p_support_uri      => 'https://example.com',
      p_token_duration   => NULL,
      p_refresh_duration => NULL,
      p_code_duration    => NULL,
      p_privilege_names  => 'my.test.priv');

   ORDS_SECURITY.GRANT_CLIENT_ROLE(
      p_client_name     => 'my.oauth.client',
      p_role_name => 'my.test.role');
COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;