
-- Generated by ORDS REST Data Services 26.2.3.r2371104
-- Schema: DEMO_USER  Date: Thu Sep 17 07:10:41 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'demo_user',
      p_auto_rest_auth      => TRUE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'records.module',
      p_base_path      => '/v1/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => 'An employee records management module consisting of various templates and handlers for performing operations on the following target tables: Department, Project, Employee.');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'records.module',
      p_pattern        => ':dept_id/:is_active?',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'An example template that will accept the query parameters dept_id and is_active. Relies on ORDS Automatic Binding to take the path parameters and use them in the provided handler code.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'records.module',
      p_pattern        => ':dept_id/:is_active?',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
    PROJ_ID,
    PROJ_NAME,
    DEPT_ID,
    IS_ACTIVE
FROM
    PROJECT
WHERE
        DEPT_ID = :dept_id
    AND ( :is_active IS NULL
          OR IS_ACTIVE = :is_active )');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'records.module',
      p_pattern        => 'emp_recs',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'records.module',
      p_pattern        => 'emp_recs',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    L_SQLCODE PLS_INTEGER;
BEGIN
    DEMO_USER.PR_ADD_AND_ASSIGN_EMPLOYEE(
        P_EMP_NAME  => :EMP_NAME,
        P_DEPT_CODE => :DEPT_CODE,
        P_COMMENTS  => :COMMENTS
    );

    COMMIT;
    :STATUS_CODE := 201;
    :RESPONSE_STATUS := ''success'';
    :RESPONSE_MESSAGE := ''Employee added.'';
EXCEPTION
    WHEN OTHERS THEN
        L_SQLCODE := SQLCODE;
        ROLLBACK;
        :STATUS_CODE :=
            CASE
                WHEN L_SQLCODE = - 20001 THEN
                    400
                ELSE
                    500
            END;
        :RESPONSE_STATUS := ''error'';
        :RESPONSE_MESSAGE :=
            CASE
                WHEN L_SQLCODE = - 20001 THEN
                    ''Department code not found.''
                ELSE
                    SQLERRM
            END;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'records.module',
      p_pattern            => 'emp_recs',
      p_method             => 'POST',
      p_name               => 'response_message',
      p_bind_variable_name => 'response_message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'records.module',
      p_pattern            => 'emp_recs',
      p_method             => 'POST',
      p_name               => 'response_status',
      p_bind_variable_name => 'response_status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.CREATE_ROLE(
      p_role_name=> 'my.test.role');
  l_roles(1) := 'my.test.role';
  l_modules(1) := 'records.module';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'my.test.privilege',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'my.test.privilege',
      p_description    => 'my.test.priv',
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;