#!/bin/bash
# Setup input variables
# USAGE:  load-atp.sh <<PASSWORD>> <<ATP_INSTANCE NAME>>  
MYPWD=$1
INSTANCE=$2
INSTANCEHIGH=${INSTANCE}_high


# Copy wallet file to Oracle user as OPC, unzip it as oracle
#sudo cp converged-wallet.zip /home/oracle
#sudo su - oracle
#mkdir wallet
#cd wallet
#unzip ../converged-wallet*

# Set oracle environment
#. oraenv << EOF
#convergedcdb
#EOF

# Set TNS_ADMIN and set sqlnet.ora
cd $HOME/wallet
export TNS_ADMIN=/home/oracle/wallet
sed -i 's|?/network/admin|/home/oracle/wallet|' sqlnet.ora

#conn admin/$MYPWD@$INSTANCEHIGH
# Begin Data Load
impdp admin/$MYPWD@$INSTANCEHIGH directory=data_pump_dir credential=def_cred_name dumpfile=https://objectstorage.us-ashburn-1.oraclecloud.com/p/ys9d6Gwudj3xLkIV-987JY2Vlyr87G_x-z-uhsPGIYio228SPw3UPAawYVAYc0ou/n/idcd8c1uxhbm/b/converged-db/o/export_appgrph22Sep2020.dmp exclude=index, cluster, indextype, materialized_view, materialized_view_log, materialized_zonemap, db_link

impdp admin/$MYPWD@$INSTANCEHIGH directory=data_pump_dir credential=def_cred_name dumpfile=https://objectstorage.us-ashburn-1.oraclecloud.com/p/9go0D1Q_eKWnazFPNOtxiz5GozJgQKRXxE7YPxTy_txhzjQYwFKkSq4yeCxCFASL/n/idcd8c1uxhbm/b/converged-db/o/export_json22Sep2020.dmp exclude=index, cluster, indextype, materialized_view, materialized_view_log, materialized_zonemap, db_link

impdp admin/$MYPWD@$INSTANCEHIGH directory=data_pump_dir credential=def_cred_name dumpfile=https://objectstorage.us-ashburn-1.oraclecloud.com/p/A2sRTp9FvVkOZSOLKCtrwrpb65E9zSkSuwE4qKQLwAsYGiXlJPex6maQ-y2RV8Wp/n/idcd8c1uxhbm/b/converged-db/o/export_appnodejs22Sep2020.dmp exclude=index, cluster, indextype, materialized_view, materialized_view_log, materialized_zonemap, db_link

impdp admin/$MYPWD@$INSTANCEHIGH directory=data_pump_dir credential=def_cred_name dumpfile=https://objectstorage.us-ashburn-1.oraclecloud.com/p/l3YpHyt_HHzyRxruvap0rbdGHSV-y5t3UX1O1MmNc9ksFZgqYljxJ2-SSGFbzVYf/n/idcd8c1uxhbm/b/converged-db/o/export_spatial22Sep2020.dmp exclude=index, cluster, indextype, materialized_view, materialized_view_log, materialized_zonemap, db_link

impdp admin/$MYPWD@$INSTANCEHIGH directory=data_pump_dir credential=def_cred_name dumpfile=https://objectstorage.us-ashburn-1.oraclecloud.com/p/euRmNrZVFn06KSHoNE1RFlL6bgAGzHHEfo5WXlph1GzhlF5fORvnvC5631dVf7zR/n/idcd8c1uxhbm/b/converged-db/o/export_xml22Sep2020.dmp exclude=index, cluster, indextype, materialized_view, materialized_view_log, materialized_zonemap, db_link

impdp admin/$MYPWD@$INSTANCEHIGH directory=data_pump_dir credential=def_cred_name dumpfile=https://objectstorage.us-ashburn-1.oraclecloud.com/p/-eBR7vx1OOSOymzKtu5tvw9G6Hkumhft-x7qsmLwBEUK-L3fj5MFnGo8FxKAwsnk/n/idcd8c1uxhbm/b/converged-db/o/analytics.dmp exclude=index, cluster, indextype, materialized_view, materialized_view_log, materialized_zonemap, db_link 

sqlplus admin/$MYPWD@$INSTANCEHIGH <<-EOF 
    CREATE TABLE "APPNODEJS"."ORDERS" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, "ORDER_DOCUMENT" "SYS"."XMLTYPE" )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255  NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS"  XMLTYPE COLUMN "ORDER_DOCUMENT" STORE AS SECUREFILE BINARY XML ( TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA;
    CREATE TABLE "APPXML"."PURCHASEORDER" OF XMLTYPE
      SEGMENT CREATION IMMEDIATE  XMLTYPE STORE AS SECUREFILE BINARY XML ( TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255  NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS"   INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW   DISTRIBUTE AUTO NO DUPLICATE ;
EOF

export TNS_ADMIN=/home/oracle/wallet

#RESTART FAILED TABLES
impdp admin/$MYPWD@$INSTANCEHIGH directory=data_pump_dir credential=def_cred_name dumpfile=https://objectstorage.us-ashburn-1.oraclecloud.com/p/euRmNrZVFn06KSHoNE1RFlL6bgAGzHHEfo5WXlph1GzhlF5fORvnvC5631dVf7zR/n/idcd8c1uxhbm/b/converged-db/o/export_xml22Sep2020.dmp exclude=index, cluster, indextype, materialized_view, materialized_view_log, materialized_zonemap, db_link table_exists_action=APPEND

impdp admin/$MYPWD@$INSTANCEHIGH directory=data_pump_dir credential=def_cred_name dumpfile=https://objectstorage.us-ashburn-1.oraclecloud.com/p/A2sRTp9FvVkOZSOLKCtrwrpb65E9zSkSuwE4qKQLwAsYGiXlJPex6maQ-y2RV8Wp/n/idcd8c1uxhbm/b/converged-db/o/export_appnodejs22Sep2020.dmp exclude=index, cluster, indextype, materialized_view, materialized_view_log, materialized_zonemap, db_link tables=APPNODEJS.ORDERS table_exists_action=APPEND


sqlplus admin/$MYPWD@$INSTANCEHIGH <<-EOF 
    grant dwrole to appjson;
    grant dwrole to analytics;
    grant dwrole to appxml;
    grant dwrole to appspat;
    grant dwrole to appnodejs;
    grant dwrole to appgrph;
    alter user appjson quota unlimited on data;
    alter user analytics quota unlimited on data;
    alter user appxml quota unlimited on data;
    alter user appspat quota unlimited on data;
    alter user appnodejs quota unlimited on data;
    alter user appgrph quota unlimited on data;

    BEGIN
      ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'appjson',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'appjson',
        p_auto_rest_auth => TRUE
      );
      COMMIT;
    END;
    /

    BEGIN
      ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'analytics',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'analytics',
        p_auto_rest_auth => TRUE
      );
      COMMIT;
    END;
    /

    BEGIN
      ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'appxml',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'appxml',
        p_auto_rest_auth => TRUE
      );
      COMMIT;
    END;
    /

    BEGIN
      ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'appspat',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'appspat',
        p_auto_rest_auth => TRUE
      );
      COMMIT;
    END;
    /

    BEGIN
      ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'appnodejs',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'appnodejs',
        p_auto_rest_auth => TRUE
      );
      COMMIT;
    END;
    /

    BEGIN
      ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'appgrph',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'appgrph',
        p_auto_rest_auth => TRUE
      );
      COMMIT;
    END;
    /

EOF 



echo "Data Load Complete"
