alter system set vector_memory_size=512M scope=spfile;

alter session set container=FREEPDB1;

CREATE USER "WALKTHROUGH" IDENTIFIED BY OrA_41_OpTIMIZER
    DEFAULT TABLESPACE "USERS"
    TEMPORARY TABLESPACE "TEMP";
GRANT "DB_DEVELOPER_ROLE" TO "WALKTHROUGH";
ALTER USER "WALKTHROUGH" DEFAULT ROLE ALL;
ALTER USER "WALKTHROUGH" QUOTA UNLIMITED ON USERS;
EXIT;